# Test your FastAPI endpoints
POST 127.0.0.1:8000/test/api/cpp_compiler
Content-Type: application/json

{
  "submission_id": 5,
  "code": "I2luY2x1ZGUgPGlvc3RyZWFtPgoKdXNpbmcgbmFtZXNwYWNlIHN0ZDsKCmludCBtYWluKCkgewogICAgaW50IFQ7CiAgICBjaW4gPj4gVDsKICAgIGNvdXQgPDwgVDsKfQo="
}

###
POST 127.0.0.1:8000/test/api/cpp_runner/
Content-Type: application/json

{
  "submission_id": 4,
  "testcases": [
    {
      "input": "1",
      "output": "1"
    },
    {
      "input": "2",
      "output": "2"
    }
  ]
}


###
POST localhost:8000/test/api/python3_compiler
Content-Type: application/json

{
  "submission_id": 3,
  "code": "cHJpbnQoIkhlbGxvIikK"
}

###
POST 127.0.0.1:8000/test/api/python3_runner/
Content-Type: application/json

{
  "submission_id": 3,
  "testcases": [
    {
      "input": "",
      "output": "1"
    },
    {
      "input": "",
      "output": "2"
    }
  ]
}

###
POST localhost:8000/test/api/jdk_compiler
Content-Type: application/json

{
  "submission_id": 9,
  "code": "cHVibGljIGNsYXNzIE1haW4gewogICAgcHVibGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykgewogICAgICAgIFN5c3RlbS5vdXQucHJpbnRsbigiSGVsbG8gV29ybGQiKTsKICAgIH0KfQ=="
}

###
POST localhost:8000/test/api/jdk_runner/8
Content-Type: application/json

{
  "submission_id": 9,
  "testcases": [
    {
      "input": "",
      "output": ""
    }
  ]
}